CREATE TABLE searchobjects (
    t_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,	
    class TEXT NOT NULL,
    id_in_class INTEGER NOT NULL,
    displaytext TEXT NOT NULL,
    searchtext_1 TEXT NOT NULL,
    searchtext_2 TEXT,
    searchtext_3 TEXT
)
;

CREATE INDEX searchobjects_1_trgm_gin ON searchobjects USING gin (searchtext_1 gin_trgm_ops);
CREATE INDEX searchobjects_2_trgm_gin ON searchobjects USING gin (searchtext_2 gin_trgm_ops);
CREATE INDEX searchobjects_3_trgm_gin ON searchobjects USING gin (searchtext_3 gin_trgm_ops);


--CREATE TABLE searchobjects (	
--    class TEXT NOT NULL,
--    id_in_class INTEGER NOT NULL,
--    displaytext TEXT NOT NULL,
--    searchtext_1 TEXT NOT NULL,
--    searchtext_2 TEXT,
--    searchtext_3 TEXT,
--    vec_1 TSVECTOR NOT NULL,
--    vec_2 TSVECTOR,
--    vec_3 TSVECTOR
--)
--;